### ISSUE TITLE
[Not an actual issue]

### ISSUE THREAD

**Issue by kryptobolt07** [SujalChoudhari/mold_os#1]
Hey mate,any resources that you would like to highlight thay are
required for building such a project?

**Comment by SujalChoudhari** [comment]
I referred to https://os.phil-opp.com/
It explains all the things that one might require to build a keyboard based input and vga output.

**Comment by kryptobolt07** [comment]
> I referred to https://os.phil-opp.com/ It explains all the things that one might require to build a keyboard based input and vga output.

Thanks
